language: python
python:
  - "3.6"
os: windows  
# command to install dependencies
install:
  - pip install -r requirements.txt
# deploy
deploy:
  provider: script
  script: pyinstaller --add-data="scrapy\mime.types;scrapy" --add-data="scrapy\VERSION;scrapy" --add-data="scrapy.cfg;." --add-data="bing;bing" --add-data="bb.cmd;." --add-data="install.cmd;." -i bing.ico -c bb.py
  on:
    branch: master